/**
 * TypeScript wrapper for WASM vCAD engine
 */

import type { MeshData } from '@/types/mesh'

// Import WASM module (will be generated by wasm-pack)
let wasmModule: any = null

export class VcadEngine {
  private ready = false

  async initialize() {
    if (this.ready) return

    try {
      // Dynamic import of WASM module
      wasmModule = await import('./pkg/vcad_engine.js')
      await wasmModule.default() // Initialize WASM

      this.ready = true
    } catch (error) {
      console.error('Failed to initialize WASM engine:', error)
      throw error
    }
  }

  private ensureReady() {
    if (!this.ready) {
      throw new Error('WASM engine not initialized. Call initialize() first.')
    }
  }

  // ========== Primitives ==========

  createCube(width: number, height: number, depth: number): string {
    this.ensureReady()
    return wasmModule.create_cube(width, height, depth)
  }

  createCylinder(radius: number, height: number): string {
    this.ensureReady()
    return wasmModule.create_cylinder(radius, height)
  }

  createSphere(radius: number): string {
    this.ensureReady()
    return wasmModule.create_sphere(radius)
  }

  createCone(radius: number, height: number): string {
    this.ensureReady()
    return wasmModule.create_cone(radius, height)
  }

  // ========== Sketch ==========

  createSketch(plane: 'XY' | 'XZ' | 'YZ'): string {
    this.ensureReady()
    return wasmModule.create_sketch(plane)
  }

  // ========== Extrude ==========

  extrudeSketch(sketchId: string, height: number, heightBackward: number, draftAngle: number): string {
    this.ensureReady()
    return wasmModule.extrude_sketch(sketchId, height, heightBackward, draftAngle)
  }

  // ========== Boolean Operations ==========

  booleanUnion(bodyId1: string, bodyId2: string): string {
    this.ensureReady()
    return wasmModule.boolean_union(bodyId1, bodyId2)
  }

  booleanDifference(bodyId1: string, bodyId2: string): string {
    this.ensureReady()
    return wasmModule.boolean_difference(bodyId1, bodyId2)
  }

  booleanIntersection(bodyId1: string, bodyId2: string): string {
    this.ensureReady()
    return wasmModule.boolean_intersection(bodyId1, bodyId2)
  }

  // ========== Sketch Operations (WASM) ==========

  trimElement(sketchJson: string, elementIndex: number, clickX: number, clickY: number): string {
    this.ensureReady()
    return wasmModule.sketch_trim_element(sketchJson, elementIndex, clickX, clickY)
  }

  offsetElement(sketchJson: string, elementIndex: number, distance: number, clickX: number, clickY: number): string {
    this.ensureReady()
    return wasmModule.sketch_offset_element(sketchJson, elementIndex, distance, clickX, clickY)
  }

  mirrorElement(sketchJson: string, elementIndex: number, axisStartX: number, axisStartY: number, axisEndX: number, axisEndY: number): string {
    this.ensureReady()
    return wasmModule.sketch_mirror_element(sketchJson, elementIndex, axisStartX, axisStartY, axisEndX, axisEndY)
  }

  linearPattern(sketchJson: string, elementIndex: number, count: number, dx: number, dy: number): string {
    this.ensureReady()
    return wasmModule.sketch_linear_pattern(sketchJson, elementIndex, count, dx, dy)
  }

  circularPattern(sketchJson: string, elementIndex: number, count: number, centerX: number, centerY: number, angle: number): string {
    this.ensureReady()
    return wasmModule.sketch_circular_pattern(sketchJson, elementIndex, count, centerX, centerY, angle)
  }

  // ========== UI Helper Functions ==========

  findElementAtPoint(sketchJson: string, pointX: number, pointY: number, threshold: number): number {
    this.ensureReady()
    return wasmModule.sketch_find_element_at_point(sketchJson, pointX, pointY, threshold)
  }

  calculateArcFrom3Points(p1x: number, p1y: number, p2x: number, p2y: number, p3x: number, p3y: number): {
    center_x: number
    center_y: number
    radius: number
    start_angle: number
    end_angle: number
    valid: boolean
  } {
    this.ensureReady()
    return wasmModule.sketch_calculate_arc_from_3_points(p1x, p1y, p2x, p2y, p3x, p3y)
  }

  getSnapPoints(sketchJson: string, cursorX: number, cursorY: number, settingsJson: string): Array<{
    x: number
    y: number
    snap_type: string
    source_element: number | null
  }> {
    this.ensureReady()
    return wasmModule.sketch_get_snap_points(sketchJson, cursorX, cursorY, settingsJson)
  }

  solveConstraints(sketchJson: string): string {
    this.ensureReady()
    return wasmModule.sketch_solve_constraints(sketchJson)
  }

  // ========== Mesh Generation (WASM) ==========

  generateCubeMesh(width: number, height: number, depth: number): MeshData {
    this.ensureReady()
    return wasmModule.generate_cube_mesh(width, height, depth)
  }

  generateCylinderMesh(radius: number, height: number): MeshData {
    this.ensureReady()
    return wasmModule.generate_cylinder_mesh(radius, height)
  }

  generateSphereMesh(radius: number): MeshData {
    this.ensureReady()
    return wasmModule.generate_sphere_mesh(radius)
  }

  generateConeMesh(radius: number, height: number): MeshData {
    this.ensureReady()
    return wasmModule.generate_cone_mesh(radius, height)
  }

}

// Singleton instance
export const engine = new VcadEngine()
